### ISSUE TITLE
nice idea

### ISSUE THREAD

**Issue by dereuromark** [chinpei215/cakephp-stackable-finder#1]
Wouldnt it be worth adding to [Shim](https://github.com/dereuromark/cakephp-shim/tree/2.x) plugin?
Or is this a too complex topic better off standalone?

**Comment by chinpei215** [comment]
Thank you for your comment! I am very surprised!
It would be worth. And I also intend to add this feature to Core If everyone hopes.
I've already implemented this feature. And I am going to add tests later.

**Comment by dereuromark** [comment]
All right. Keep me posted in case you want to either put it into Shim or me referencing it somewhere. 
Sounds like this makes the two major CaePHP versions less distant from each other :)

**Comment by chinpei215** [comment]
I understood. I will notify you. For now, I still use cake 2 in my works. But as you mentioned, this plugin can make the code modern :)

**Comment by dereuromark** [comment]
Yeah I also have to still maintain 2 large legacy 2.x apps, but already prepare them to be as 3.x upgradable as possible. And hopefully next year I can switch those, too.

**Comment by chinpei215** [comment]
I had a similar thought as you. Next, I am going to create a plugin for using [ORM](https://github.com/cakephp/orm) in cake2.

**Comment by dereuromark** [comment]
Cool, all right.
